### ISSUE TITLE
Maven repo after renanming

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis-official-plugins#49]
The plugins are not available on the maven repo since orbisgis-official-plugins.
So Jenkins is not able to build the R-console plugin.
See
http://jenkins.orbisgis.org/job/r-console/178/console

**Comment by nicolas-f** [comment]
```Could not find artifact org.orbisgis:orbisgis-official-plugins:pom:5.1```

There is no jenkins goal to make and publish the main pom.

You should not create a jenkins goal for each sub-project but a single one by repository.

**Comment by ebocher** [comment]
Fixed thanks a lot  @nicolas-f
