### ISSUE TITLE
Guidelines - Add docs for each plugins

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis-official-plugins#56]
In order to improve our documentation, we should define a guideline that describe the ressources we should associate to each plugins code.
For example, we should add the following elements in each plugins folder:
- a `README.md` file, in which we have the plugin's documentation (how to install / use ?)
- an `img` folder, in which all illustrations used in the README.md will be stored
- a `pom.xml` file
- an `src` folder

This guideline should be displayed in the main `README.md` of `orbisgis-official-plugins`

We should also think about the translation. So we can have something like this:
- a `README_EN.md`
- a `README_FR.md`
- ...

What do you think guys ? @ebocher @SPalominos @nicolas-f 
I can manage if you want.

**Comment by nicolas-f** [comment]
I think you are talking about third parties contributors for plugins ? Did you create this issue because you receive a feedback about creating plugins for OrbisGIS ?

**Comment by gpetit** [comment]
No, I created this issue because I'm working on doc.orbisgis.org and I was wondering where was the best place to describe our plugins. After exchanges with @ebocher we think that the best way is to add documentation close to the code, in each plugins folder, via the README.md

**Comment by gpetit** [comment]
Here is a "small" example of what we can except with the README.md https://github.com/orbisgis/orbisgis-official-plugins/tree/master/mailto

**Comment by gpetit** [comment]
In the meantime, @ebocher think that it will be possible then in OG to download this doc and to display it directly in OG (in the Plugin Manager ?)

**Comment by nicolas-f** [comment]
Yes, the description of plugins are done in the pom.xml of each plugins.

**Comment by gpetit** [comment]
Yes, this is a formated description.
But here, i'm mainly speaking about the user documentation

**Comment by nicolas-f** [comment]
You can also provide a link in order to show it the default browser (maybe more convenient)

**Comment by nicolas-f** [comment]
The official tag ```Bundle-DocURL``` could be appropriate.

https://www.osgi.org/bundle-headers-reference/

**Comment by ebocher** [comment]
Good idea. The url must be set according the OrbisGIS local to point out the readme (fr or es...)

**Comment by gpetit** [comment]
Concerning the translation of README.md, I made a test (in the MailTo plugin).
Only the README.md is display as a documentation in the main page.
The README_FR.md is only displayed if you click on it. So it's perfect.

By default, the doc should be in english, in the README.md files and additionnal translations can be in README_XX.md files.

**Comment by gpetit** [comment]
@ebocher it also mean that wiki pages (https://github.com/orbisgis/orbisgis-official-plugins/wiki) will be moved in their respective plugins.
It makes more sense for me

**Comment by gpetit** [comment]
Ok so I'm on it

**Comment by gpetit** [comment]
Here we are.
* Docs have been mooved to their respectives folders,
* Undocumented plugins have been documented,
* The master '[README.md](https://github.com/orbisgis/orbisgis-official-plugins/blob/master/README.md)' file has been updated in order to explain how to install a plugin
* The [wiki](https://github.com/orbisgis/orbisgis-official-plugins/wiki) has been updated
    * home page has been refreshed
    * wiki pages for 'R Console, 'ChartView', 'SQL Console' and 'Groovy Console' have been deleted

@ebocher I think you can close this issue
