### ISSUE TITLE
MapComposer does not work

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis-official-plugins#58]
I'm using the PPA release of OG.
I just installed the Map Composer plugin.
I imported the DEPARTEMENT.shp file and displayed it in my map. The content is saved in MaCarte.ows

In the MapComposer plugin, I created a new document. Then I click on the "map" icon in order to add my .ows context.

![map_composer](https://cloud.githubusercontent.com/assets/1871248/23995853/aa543218-0a4b-11e7-8ae7-ab24a362983f.png)

Here, nothing appears and in OG, I have the following error message:

```
Unable to load the data source uri file:/usr/Documents/SIG/GEOFLA_2-0_DEPARTEMENT_SHP_LAMB93_FXX_2015-03-23/GEOFLA/1_DONNEES_LIVRAISON_2015-03-00396/GEOFLA_2-0_SHP_LAMB93_FR-ED141/DEPARTEMENT/DEPARTEMENT.SHP.
Cannot draw  the table does not exists
Cannot compute layer envelope:
The table "" does not contain a Geometry field, then the extent cannot be computed
Unable to load the data source uri file:/usr/Documents/SIG/GEOFLA_2-0_DEPARTEMENT_SHP_LAMB93_FXX_2015-03-23/GEOFLA/1_DONNEES_LIVRAISON_2015-03-00396/GEOFLA_2-0_SHP_LAMB93_FR-ED141/DEPARTEMENT/DEPARTEMENT.SHP.
```

Note that my DEPARTEMENT layer is imported (not linked). I also tried to create a spatial index ... and the pblm is the same.

@ebocher

**Comment by ebocher** [comment]
it seems related to https://github.com/orbisgis/orbisgis/issues/1208
