### ISSUE TITLE
REngineFactory add orbisgis repo

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis-official-plugins#60]
As explained here http://docs.renjin.org/en/latest/library/execution-context.html, Renjin is able to load several Maven repository.
What about adding repo.orbisgis.org in the method
RenjinScriptEngine createRScriptEngine()

**Comment by SPalominos** [comment]
Ok, I will do it.

**Comment by ebocher** [comment]
Is it solved ?

**Comment by SPalominos** [comment]
I'm on it

**Comment by SPalominos** [comment]
Fixed
