### ISSUE TITLE
RandomForest - RENJIN bug

### ISSUE THREAD

**Issue by ebocher** [orbisgis/orbisgis-official-plugins#64]
The Renjin dependency must be updated with the last release in order to solve the bug 
```
"Cannot execute this R script.
Cause : Don't know how to marshall type org.renjin.primitives.matrix.TransposingMatrix to for C argument interface org.renjin.gcc.runtime.Ptr in call to MethodHandle(Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr,Ptr)void"

```

@j3r3m1

**Comment by SPalominos** [comment]
The update of renjin to version 0.8.2515 is done and should resolve the issue.

**Comment by j3r3m1** [comment]
The issue is solved, the R-script can be run after updating Renjin. However, a new error message appear when executing a Groovy script calling Renjin

> Could not load package RH2GIS; tried org.renjin.bioconductor:RH2GIS, org.renjin.cran:RH2GIS

**Comment by ebocher** [comment]
oupss. A dependency pb with RDBI I will look on it

**Comment by ebocher** [comment]
The script below has been successfully tested with Renjin studio  0.8.2515 . 

```r
library(RH2GIS)
con <- dbConnect(RH2GIS(), url="jdbc:h2:file:/tmp/mydb", username="sa", password="")
loadSpatialFunctions(con)
#Create a table with a geometry column
dbSendQuery(con,"CREATE TABLE VANNES (the_geom geometry, id int)")
#Insert a polygon
dbSendQuery(con,"INSERT INTO VANNES VALUES('POLYGON ((100 300, 210 300, 210 200, 100 200, 100 300))'::geometry, 1)"); 
#Run a spatial function
df  <- dbGetQuery(con,"SELECT ST_AREA(the_geom) as area FROM VANNES")
```
Works also in OrbisGIS RConcole.

**Comment by SPalominos** [comment]
It seems that the package RH2GIS has been removed from the Renjin repositories : the search for [RH2GIS](http://packages.renjin.org/packages/search?q=RH2GIS) doesn't return any result while [RH2](http://packages.renjin.org/packages/search?q=RH2) does. So if the **RH2GIS** dependency is not in the maven local, **Renjin** is not able to find it in the remote package repositories.

There is a workaround to solve the problem by compiling RH2GIS locally: 
1) Install if not present the the following tools : **maven** ,**git**, and the good version of the **JDK**.
On linux you can run the command `sudo apt-get install maven git openjdk-8-jdk`
2) Clone the **Renjin DBI** project with `git clone https://github.com/hannesmuehleisen/renjin-dbi`
3) Compile **Renjin DBI**  with `mvn install -DskipTests`
4) Open OrbisGIS and install the **R console** plugin
5) Execute in the R console the command `library(RH2)` which download the **RH2** package (which is the only dependency of **RH2GIS**) and its dependencies.
6) Run in the **R console** `library(RH2GIS)` and check that the command run properly.

**Comment by ebocher** [comment]
Explanation here https://groups.google.com/forum/#!msg/renjin-dev/xh6jmNulmLI/2hGgQQb9AAAJ
